### PR TITLE
Couple of corrections and JQuery Slideshow

### PR DESCRIPTION
**Pull request by MarkelFe**
For this pull request I have done a couple of edits:

1. I had first reordered the files to a format that it will be easier with navigate with and help with upgradability. It also is a more standard format, so newcomers will have an easier adaptation. 

2. Delete the index.html redirection file, as it is much easier to create a website that uses `@media` in CSS as you only have to create a single website which reduces the workload.

3. I have changed the tag `<center>` to `<body>` [as it is decrapted](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center), if it's necessary to include the effect again it can always be done with `style="text-align:center"`. I also removed some other tags that were unnecessary.

4. I replaced the CSS animation that was being used with a animation using JS, [as it's recommended for endless animations.](https://developers.google.com/web/fundamentals/design-and-ux/animations/css-vs-javascript) The script that is being used for the animation is located in `js/slideshow.js`, the script detects the number of slides so no code change is necessary. However, the time between slides can be changed on line 20 and the duration of the animation on lines 6&7. For adding more slides it's only necessary to create more `` tags, with some properties that are stated on line 14 (index.html)

5. I also took care about the LightHouse results (you can find it on the Audits section of the Chrome console). The settings were set to Desktop; Simulated Fast 3G, 4x CPU Slowdown; Storage cleared (although probably JQuery will be in the cache of many of many browsers as we use the hosted Google repository). The results also contain how many points have we got compared to the current public version:

     - Permormance: 98    ⯅ 9
     - Progressive Web Apps: 58   ⯅0
     - Accessibility: 100   ⯅9
     - Best Practises: 93   ⯅0
     - SEO: 89   ⯅0

### To do:

- [ ] Add meta description, that will increase the possibilities of appearing in first results on search engines. I would do it myself, but I think that the description should be decided by the group.
- [ ] Create a minified version.
- [ ] Take care of not maintaining the aspect ratio of the images.
- [ ] Change the format of the image to others than require less space, for increasing the performance and reduce the data usage.
- [ ] Maybe add a theme-color.
- [ ] Finish the website.
- [ ] Make the page responsible for all kind of devices

These are some ideas that I had, I will create the corresponding issues. I encourage you to create also issues if you want to the present an idea (it also works as a note program). You can watch a life demo of this pull request [here](https://markelfe.github.io/frc7787/). If you have any doubt or you want to comment anything about the pull request, feel free to leave a comment.

### CODE REVIEW

**Comment by kkarim** [comment]
Come into the lab 112 during A block if possible, and we'll get you talking
to Connor about how to use github.

**Comment by kkarim** [comment]
Oh, actually, Connor is in B block! Does that work for you? Alternatively,
lunch time or after school. It'll be more useful if you're sitting next to
each other, both logged into GitHub, so Connor can see how the process
works.

**Comment by MarkelFe** [comment]
Please merge the pull request 😅. Approving it doesn't apply the changes.

**Comment by wildmeese** [comment]
I need the command line to do it, so I’ll set up the desktop app sometime

Thanks,

Connor

**Pull request merged**
