### PR TITLE
Delete placeholders and navbar

### PR DESCRIPTION
**Pull request by MarkelFe**
Hi, I have been working on deleting the placeholders and I also edit the navbar so it's more readable. I have deleted the links (don't worry I have only comment them), as they requested on the meeting, we are gonna be able to go adding them as we finish that sections. Also, I would want to create a branch called dev (or something similar). We have to remember that the site is already live and it wouldn't give a good reputation having strange things on our website.

PD: Even if Github says that the pull request is not mergeable, don't worry I have tested. It's only that we have deleted stuff in a different order, but the end result is the same.

### CODE REVIEW

**Comment by wildmeese** [comment]
I'm pretty sure that the CNAME is not something we want to delete, but if it is please explain to me why

**Comment by wildmeese** [comment]
I’ll just not delete it when I merge, thanks

Thanks,

Connor

**Comment by wildmeese** [comment]
so turns out i have no idea how to fix the conflicts with the command line

**Comment by MarkelFe** [comment]
Don't worry, merge it completely and commit the CNAME directly with a different commit. Basically delete and add ^^. 

Sorry for giving you so much problem

**Comment by wildmeese** [comment]
The CNAME doesn’t mess anything up, I just don’t know how to fix all the other conflicts

**Comment by MarkelFe** [comment]
Now you should be able to merge the pull request. I have resolved the conflicts.

**Comment by kkarim** [comment]
Merged.

**Pull request merged**
